title: My Sample Blog
author: ubitoffee
email: ubi.toffee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I wanna be a nice programmer

# social links
twitter_username: your-twitter-handle
github_username:  ubitoffee

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

